# Generated by Django 5.0.4 on 2024-04-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exame",
            fields=[
                ("id_exame", models.AutoField(primary_key=True, serialize=False)),
                ("nome_exame", models.TextField()),
                ("data_exame", models.DateField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_modificacao", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.TextField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("senha", models.TextField(max_length=40)),
            ],
        ),
    ]
