# Generated by Django 5.0.4 on 2024-04-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_cad_exames", "0002_exame_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="exame",
            name="email",
            field=models.EmailField(default=0, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
